### ISSUE TITLE
KeyError: 'd'

### ISSUE THREAD

**Issue by ghost** [lvoegtlin/svg_to_page#1]
@lvoegtlin 

When I run `converter.py` in the environment I get error:
```
(convert_svg_to_page) home@home-desktop:~/programs/svg_to_page-master$ python converter.py --input_folder ./input --output_folder ./output
Traceback (most recent call last):
  File "converter.py", line 65, in <module>
    convert(args.input_folder, args.output_folder)
  File "converter.py", line 24, in convert
    coords_string = parse_file_and_convert(input_path, file)
  File "converter.py", line 38, in parse_file_and_convert
    coordinates = child.attrib['d']
KeyError: 'd'
```

**Comment by ghost** [comment]
@Renthal Do you have any idea on how to solve this?
because this might come in-handy when training

**Comment by Renthal** [comment]
What do you mean by training?
Anyway without seeing your svg file is hard to say. The error is a KeyError thus it says that there is not the key “d” in your paraed svg. It is probably a naming issue i assume?

___________________________________________
Michele Alberti
Ph.D Candidate at University of Fribourg
Document Image Voice Analysis Group
Tel. +41 76 224 75 58<tel:+41%2076%20224%2075%2058>
albertimichele91@hotmail.com<mailto:albertimichele91@hotmail.com>
michele.alberti@unifr.ch<mailto:michele.alberti@unifr.ch>
.
...:

On 8 Aug 2019, at 23:10, deepseek <notifications@github.com<mailto:notifications@github.com>> wrote:


@Renthal<https://github.com/Renthal> Do you have any idea on how to solve this?
because this might come in-handy when training

**Comment by ghost** [comment]
@Renthal  here is an svg file example
[test1.svg.zip](https://github.com/lvoegtlin/svg_to_page/files/3483948/test1.svg.zip)

**Comment by ghost** [comment]
@Renthal IF THE ORIGINAL ENVIRONMENT NOT WORKING , then try this:

[environment.yml.zip](https://github.com/lvoegtlin/svg_to_page/files/3486717/environment.yml.zip)
conda env create -f environment.yml
conda activate convertsvg

**Comment by ghost** [comment]
@Renthal so did you have a look?

**Comment by ghost** [comment]
@lvoegtlin
